server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 12345678
  session:
    store-type: none
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
cp:
  browser:
    loginpage: /demo-signIn.html
    resptype: JSON