spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze0803j8f23nryj3go.mysql.rds.aliyuncs.com:3306/li_test?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: liweiwei
    password: QWEqwe123
  session:
    store-type: none
  security:
    user:
      name: admin
      password: 123456